<a href="https://colab.research.google.com/github/Victonier/CS501_A3/blob/main/Pytorch_Tutorial_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import print_function
import torch
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed



Section 1: Tensors
================
Please refer: https://pytorch.org/docs/stable/tensors.html

A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

<b>Task 1: Constructing Tensors</b>

a) Construct a 5x3 matrix, uninitialized:



In [2]:
# The shape of the tensor is defined by the variable argument size
# Tensor is initialized with garbage values
x = torch.empty(5, 3)
print(x)

tensor([[2.1715e-18, 3.3089e-09, 2.0663e+20],
        [1.6411e-07, 5.3179e+22, 7.9874e+20],
        [1.0528e-11, 4.2656e-08, 6.7127e-07],
        [8.2293e-10, 2.1707e-18, 4.5447e+30],
        [7.0062e+22, 2.1715e-18, 4.5447e+30]])


b) Construct a randomly initialized matrix:



In [3]:
x = torch.rand(5, 3)
print(x)
print(x.size())

tensor([[0.2535, 0.2184, 0.3719],
        [0.0329, 0.8561, 0.2089],
        [0.1904, 0.2212, 0.6449],
        [0.9734, 0.2642, 0.3716],
        [0.7144, 0.9342, 0.1218]])
torch.Size([5, 3])


c) Construct a matrix filled zeros and of dtype long:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


d) Construct a tensor directly from data:



In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


e) Create a tensor based on an existing tensor. 

Note: These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user



In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

# Generates random values from Normal distribution
# Uses the shape of the given tensor
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2237, -1.3459, -0.0398],
        [-0.9023, -0.7328,  1.1682],
        [-1.3230,  0.9583, -0.8185],
        [ 1.5355, -0.2616, -0.7398],
        [ 0.8211, -0.3771,  0.5974]])


<b>Task 2: Get the size of the tensor </b>

Note: torch.Size is in fact a tuple, so it supports all tuple operations.



In [7]:
print(x.size())
# print(x.size())

torch.Size([5, 3])


<b>Task 3: Operations</b>

a) Addition: syntax 1



In [8]:
p = torch.rand(5, 3)
q = torch.rand(5, 3)
print(p + q)

tensor([[1.6648, 0.8435, 0.8919],
        [1.0647, 0.7403, 1.4900],
        [0.9053, 0.5168, 1.2172],
        [0.6932, 0.4858, 1.0209],
        [1.1949, 1.0344, 0.9690]])


b) Addition: syntax 2



In [9]:
print(torch.add(p, q))

tensor([[1.6648, 0.8435, 0.8919],
        [1.0647, 0.7403, 1.4900],
        [0.9053, 0.5168, 1.2172],
        [0.6932, 0.4858, 1.0209],
        [1.1949, 1.0344, 0.9690]])


c) Addition: providing an output tensor as argument



In [10]:
result = torch.empty(5, 3)
torch.add(p, q, out=result)
print(result)

tensor([[1.6648, 0.8435, 0.8919],
        [1.0647, 0.7403, 1.4900],
        [0.9053, 0.5168, 1.2172],
        [0.6932, 0.4858, 1.0209],
        [1.1949, 1.0344, 0.9690]])


d) Addition: in-place



In [11]:
# adds x to y
q.add_(p)
print(q)

tensor([[1.6648, 0.8435, 0.8919],
        [1.0647, 0.7403, 1.4900],
        [0.9053, 0.5168, 1.2172],
        [0.6932, 0.4858, 1.0209],
        [1.1949, 1.0344, 0.9690]])


Note: Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

<b>Task 4: Misc Operations </b>

a) Indexing



In [ ]:
print(result)
print(result[:, 1])

tensor([[1.3518, 0.7396, 1.7066],
        [0.5235, 1.6642, 0.3787],
        [1.3237, 1.0827, 0.5181],
        [0.9051, 1.0894, 1.7650],
        [1.3346, 1.0409, 0.3504]])
tensor([0.7396, 1.6642, 1.0827, 1.0894, 1.0409])


b) Resizing



In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


c) Permute

Used for image data where order of data is important

In [ ]:
x = torch.randn(3,224,224)
y = x.permute(1,2,0)
print(x.size(), y.size())

torch.Size([3, 224, 224]) torch.Size([224, 224, 3])


d) Accessing 



In [ ]:
x = torch.randn(1) # std norm dist vs rand: uniform [0,1)
print(x)
print(x.item()) # works for tensors with single value

x = torch.randn(2, 2)
print(x)
print(x.tolist()) # works for tensors with multiple values

tensor([-2.3965])
-2.3964662551879883
tensor([[ 0.9251,  0.7056],
        [ 0.1914, -0.2224]])
[[0.9250897765159607, 0.7056499719619751], [0.19139954447746277, -0.2224278450012207]]


Section 2: NumPy 
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

a) Converting a Torch Tensor to a NumPy Array




In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

Note: See how the numpy array changed in value.



In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


b) Converting NumPy Array to Torch Tensor

Note: see how changing the np array changed the Torch Tensor automatically



In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

Section 3: CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
# Devices available are 'cuda' and 'cpu'

x = torch.rand(5,3)
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[1.7038, 1.5289, 1.1912],
        [1.9412, 1.0138, 1.8623],
        [1.9674, 1.4602, 1.4017],
        [1.2006, 1.5367, 1.5383],
        [1.9503, 1.4044, 1.2570]], device='cuda:0')
tensor([[1.7038, 1.5289, 1.1912],
        [1.9412, 1.0138, 1.8623],
        [1.9674, 1.4602, 1.4017],
        [1.2006, 1.5367, 1.5383],
        [1.9503, 1.4044, 1.2570]], dtype=torch.float64)
